[package]
name = "Bostree"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"

[lib]
path = "src/lib.rs"

[[test]]
name = "remove_bug"
path = "src/bin/remove_bug.rs"

[[test]]
name = "remove_bug_2"
path = "src/bin/remove_bug_2.rs"

[[test]]
name = "timing"
path = "src/bin/timing.rs"
