[package]
name = "proj_42_Kocaeli_Printf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.proj_42_Kocaeli_Printf-lang.org/cargo/reference/manifest.html

[dependencies]




















